### ISSUE TITLE
Allow plugin to be deleted

### ISSUE THREAD

**Issue by terrytibbles** [nstaeger/wp-post-email-notification#17]
Hello,

I realise that this plugin is (probably) no longer supported, but can you update it, to allow deletion of the plugin, in later versions of Wordpress?

If I try to delete it through the Wordpress plugin page, I get an 'Deletion failed: There has been a critical error on your website' message and the following in the PHP log:

```
[23-May-2020 11:15:35 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Nstaeger\WpPostEmailNotification\Model\JobModel::__construct(), 1 passed in /home/user/public_html/travel/wp-content/plugins/wp-post-email-notification/uninstall.php on line 24 and exactly 2 expected in /home/user/public_html/travel/wp-content/plugins/wp-post-email-notification/src/Model/JobModel.php:23
Stack trace:
#0 /home/user/public_html/travel/wp-content/plugins/wp-post-email-notification/uninstall.php(24): Nstaeger\WpPostEmailNotification\Model\JobModel->__construct(Object(Nstaeger\CmsPluginFramework\Broker\Wordpress\WordpressDatabaseBroker))
#1 /home/user/public_html/travel/wp-admin/includes/plugin.php(1222): include('/home/user/...')
#2 /home/user/public_html/travel/wp-admin/includes/plugin.php(956): uninstall_plugin('wp-post-email-n...')
#3 /home/user/public_html/travel/wp-admin/includes/ajax-actions.php(4545): delete_plugins(Array)
#4 /home/user/public_html/travel/wp-includes/class-wp-hook.php(287): wp_ajax_de in /home/user/public_html/travel/wp-content/plugins/wp-post-email-notification/src/Model/JobModel.php on line 23
```
Thanks.

**Comment by terrytibbles** [comment]
Any chance of an update @nstaeger?
